### ISSUE TITLE
Mollie payment gateway requires testing

### ISSUE THREAD

**Issue by SimSync** [e107inc/vstore#103]
Just added support for the Mollie (https://www.mollie.com) payment gateway.
This gateway still needs testing as it requires a valid business during registration (which i'm unable to provide).

**Comment by SimSync** [comment]
See PR https://github.com/e107inc/vstore/pull/104/

Would be great is somebody is able to test this implementation as it provides several payment providers incl. SEPA transfers, Klara, etc.

**Comment by SimSync** [comment]
So far, in test mode everything is working.
Would be great if someone who is using some of Mollie's payment services in production can confirm that.

**Comment by Alex-e107nl** [comment]
Hi SimSync, i want to test it but there's directly a problem, will make a new issue...
Implementating Molie is what i needed to use the Vstore...

**Comment by Alex-e107nl** [comment]
Oke, been busy with it, i have a Mollie account and i am testing with the git version of Vstore, it seems that in the English language everything works fine, i can make a test payment and everything works fine, next i changed the language in the admin of e107 to dutch, i get a blanc screen on the last Buy now button, found in my server logs the next message, looks like the , and . (that changes with the Dutch language) gives a problem.

[Fri Dec 02 13:27:53.693399 2022] [proxy_fcgi:error] [pid 363989:tid 140339994158848] [client 87.87.133.136:59767] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Invalid integer part 7,2. Invalid digit , found in /home/********/domains/e107.nl/private_html/e107_plugins/vstore/vendor/moneyphp/money/src/Number.php:256\nStack trace:\n#0 /home/********/domains/e107.nl/private_html/e107_plugins/vstore/vendor/moneyphp/money/src/Number.php(37): Money\\Number::parseIntegerPart()\n#1 /home/********/domains/e107.nl/private_html/e107_plugins/vstore/vendor/moneyphp/money/src/Number.php(50): Money\\Number->__construct()\n#2 /home/********/domains/e107.nl/private_html/e107_plugins/vstore/vendor/omnipay/common/src/Common/Message/AbstractRequest.php(282): Money\\Number::fromString()\n#3 /home/********/domains/e107.nl/private_html/e107_plugins/vstore/vendor/omnipay/common/src/Common/Message/AbstractRequest.php(315): Omnipay\\Common\\Message\\AbstractRequest->getMoney()\n#4 /home/********/domains/e107.nl/private_html/e107_plugins/vstore/vendor/omnipay/mollie/src/Message/Request/PurchaseRequest.php(77): Omnipay\\Comm...', referer: https://e107.nl/vstore/checkout/

Hope this helps to get it right! (Tgtje does know it also now...)
