### ISSUE TITLE
Other popular payment methods

### ISSUE THREAD

**Issue by parsfounder** [e107inc/vstore#173]
Skrill and Stripe are one of the most popular digital wallets in the market and not included in vstore plugin yet.

**Comment by realmontazeri** [comment]
This decentralized API looks nice! https://github.com/bitcoinz-wallets
No signup is required and multi-currency support

**Comment by realmontazeri** [comment]
Authorize.Net and 2Checkout are another examples

**Comment by CaMer0n** [comment]
@realmontazeri Would you be willing to test Skrill and Stripe if I can get this added?

**Comment by CaMer0n** [comment]
@realmontazeri Omnipay isn't a payment gateway, it is a code library.  I have to add code to add the support. 

> @realmontazeri Would you be willing to test Skrill and Stripe if I can get this added?

**Comment by realmontazeri** [comment]
Several payment gateways were added recently, special thanks to @CaMer0n for his amazing job!

**Comment by CaMer0n** [comment]
Thanks @realmontazeri. And for reference, here they all are: 

![image](https://user-images.githubusercontent.com/2825679/106374087-8f62d400-6334-11eb-8a9f-bdfa4170dcd9.png)

**Comment by 2548ir** [comment]
> @realmontazeri Would you be willing to test Skrill and Stripe if I can get this added?

@CaMer0n I am currently using Stripe and Coinpayments which they are working properly.

**Comment by CaMer0n** [comment]
@parsfounder Thank you for the feedback! :+1:

**Comment by parsfounder** [comment]
stripe: Fatal error: Uncaught Omnipay\Common\Exception\InvalidRequestException: The source parameter is required in /home/.../plugins/vstore/vendor/omnipay/common/src/Common/ParametersTrait.php:81 Stack trace: #0 /home/.../plugins/vstore/vendor/omnipay/stripe/src/Message/AuthorizeRequest.php(315): Omnipay\Common\Message\AbstractRequest->validate('source') #1 /home/.../plugins/vstore/vendor/omnipay/common/src/Common/Message/AbstractRequest.php(686): Omnipay\Stripe\Message\AuthorizeRequest->getData() #2 /home/.../plugins/vstore/vstore.class.php(1837): Omnipay\Common\Message\AbstractRequest->send() #3 /home/.../plugins/vstore/vstore.class.php(684): vstore->processGateway() #4 /home/.../plugins/vstore/vstore.class.php(290): vstore->p in /home/.../plugins/vstore/vendor/omnipay/common/src/Common/ParametersTrait.php on line 81
![Screenshot_20220507_015454](https://user-images.githubusercontent.com/10089685/167218913-afd8864d-fa49-498d-b47c-10feec567fea.png)
coinpayments: Fatal error: Uncaught Error: Call to undefined method Omnipay\Coinpayments\Gateway::purchase() in /home/.../plugins/vstore/vstore.class.php:1837 Stack trace: #0 /home/.../plugins/vstore/vstore.class.php(684): vstore->processGateway() #1 /home/.../plugins/vstore/vstore.class.php(290): vstore->process() #2 /home/.../plugins/vstore/vstore.php(41): vstore->init() #3 /home/.../index.php(69): include_once('/home/clients/9...') #4 {main} thrown in /home/.../plugins/vstore/vstore.class.php on lin
![Screenshot_20220507_015436](https://user-images.githubusercontent.com/10089685/167218980-3718bc85-dc48-42f5-8082-94437346eb9c.png)
e 1837

**Comment by parsfounder** [comment]
> @parsfounder Would you happen to know exactly WHEN those payment methods stopped working?

@CaMer0n this happened after updating e107 and vstore to the latest version, the issue actually appears on the page right after confirming address and basket info
